- name: type:feature
  color: "2E86AB"
- name: type:fix
  color: "E67E22"
- name: type:hotfix
  color: "C0392B"
- name: type:release
  color: "8E44AD"
- name: sync:release→develop
  color: "95A5A6"
- name: priority:high
  color: "D35400"
- name: versioning:semver
  color: "27AE60"
- name: guard:override
  color: "7F8C8D"
- name: size/XS
  color: "B3E5FC"
- name: size/S
  color: "81D4FA"
- name: size/M
  color: "4FC3F7"
- name: size/L
  color: "29B6F6"
- name: size/XL
  color: "03A9F4"
