name: PR Validation (Title Only)

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Validate PR Title (Conventional)
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const title = pr.title || '';
            const prNumber = pr.number;

            // 규칙:
            // 1) Conventional types (+scope 선택): type(scope): summary 또는 type: summary
            // 2) hotfix: summary (핫픽스 전용 패턴 지원)
            // 3) release: vX.Y.Z 또는 release: text (간소 지원)
            const conventional = /^(feat|fix|refactor|perf|test|docs|chore)(\([\w\-\/]+\))?:\s.+$/i;
            const hotfix = /^hotfix:\s.+$/i;
            const release = /^release:\s.+$/i; // 버전 정규식 강화는 필요 시 확장

            const ok = conventional.test(title) || hotfix.test(title) || release.test(title);

            if (ok) {
              console.log('Title valid:', title);
              return;
            }

            const msg = '❌ **PR 제목 형식 위반**\n\n' +
              '다음 중 하나의 형식을 따라주세요:\n' +
              '- `type(scope): summary`\n' +
              '- `type: summary`\n' +
              '- `hotfix: summary`\n' +
              '- `release: v1.2.3`\n\n' +
              '현재 제목: `' + title + '`';

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: msg
            });

            // 규칙 미준수일 때만 차단
            core.setFailed('PR 제목이 규칙에 맞지 않습니다. 제목을 수정해주세요.');
